name: hybrid_map_marker
description: "A Flutter package that allows you to create custom map markers from any widget for use with Google Maps."
version: 1.0.1
homepage: https://github.com/rudoapps/hybrid-map-marker
repository: https://github.com/rudoapps/hybrid-map-marker
issue_tracker: https://github.com/rudoapps/hybrid-map-marker/issues

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  google_maps_flutter: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0